<?php $title = "delete " . $this->person->getName() ?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to <?php echo $this->escapeHtml($title); ?>
 </p>
 <?php
 $url = $this->url('person', array(
     'action' => 'delete',
     'id'     => $person->getId(),
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $person->getId(); ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>
