<h1>List of registered persons</h1>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Role</th>
      <th>Name</th>
      <th>Comment</th>
      <th>Access Code</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($persons as $person): ?>
    <tr>
      <td><?=$person->getRole();?></td>
      <td><?=$person->getName();?></td>
      <td><?=$person->getComments();?></td>
      <td><?=$person->getCode();?></td>
      <td><a href="<?php echo $this->url('person', array('action'=>'edit', 'id' => $person->getId()));?>">
            <button type="button" class="btn btn-primary">edit</button>
          </a>
      </td>
      <td><a href="<?php echo $this->url('person', array('action'=>'delete', 'id' => $person->getId()));?>">
            <button type="button" class="btn btn-danger">delete</button>
          </a>
      </td>
      <td><a href="<?php echo $this->url('person', array('action'=>'log', 'id' => $person->getId()));?>">
            <button type="button" class="btn btn-info">log</button>
          </a>
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
<a href="<?php echo $this->url('person', array('action'=>'create'));?>">
  <button type="button" class="btn btn-success">create</button>
</a>
