<h1><?php echo $this->escapeHtml($this->person->getName()); ?></h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>time</th>
      <th>entry</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($log as $l): ?>
    <tr>
      <td><?php echo $l->getLogtime()->format('Y-m-d H:i:s'); ?></td>
      <td><?php echo $this->escapeHtml($l->getEntry()); ?></td>
    </tr>
  <?php endforeach; ?>
 </tbody>
</table>
