<div class="row top-buffer">
  <div class="col-md-4">

    <div class="bs-example" data-example-id="simple-carousel">
      <div class="carousel slide" id="carousel-<?= $id ?>" data-ride="carousel">
         <ol class="carousel-indicators">
           <?php for ($i=0; $i < count($images); $i++): ?>
             <li data-target="#carousel-<?= $id ?>" data-slide-to="<?= $i ?>" class="<?php if($i == 0): ?>active<?php endif; ?>"></li>
           <?php endfor; ?>
         </ol>
         <div class="carousel-inner" role="listbox">
          <?php for ($i=0; $i < count($images); $i++): ?>
          <div class="item <?php if($i == 0): ?>active<?php endif; ?>">
            <img class="carousel-img" src="<?php echo $this->url('file', ['id' => $images[$i]]); ?>">
          </div>
          <?php endfor; ?>

        </div>
        <a href="#carousel-<?= $id ?>" class="left carousel-control" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a href="#carousel-<?= $id ?>" class="right carousel-control" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>

  </div>
  <div class="col-md-8">
    <?= $text; ?>
  </div>
</div>
